---
- hosts: droplet
  remote_user: root
  gather_facts: no

  vars_files:
    - vars/vars.yml

  pre_tasks:
    - name: Update aptitude
      apt: update_cache=yes

  roles:
    - common
    - swap
    - ntp
    - nginx
    - php-fpm
    - mysql
    - ansible-composer
    - drush