---
- hosts: droplet
  remote_user: root

  vars_files:
    - vars/vars.yml

  pre_tasks:
    - name: Update aptitude
      apt: update_cache=yes

  roles:
    - common
    - swap
    - ntp
    - fail2ban
    - nginx
    - ssl
    - php-fpm
    - hhvm
    - mariadb
    - drush
    - phpcodesniffer
    - nodejs
    - postfix
    - jenkins
    - gitlab