---
- hosts: droplet
  remote_user: root
  gather_facts: no

  tasks:
    - name: Uninstall all packages
      apt: >
        pkg={{ item }} 
        state=absent
        purge=yes
        force=yes
      with_items:
        - nginx*
        - mysql*
        - php*
        - git*
        - zsh*
      sudo: yes

    - user: name={{ user }} state=absent remove=yes

    - name: Set sh as default shell
      user: name=root shell=/bin/sh

    - group: name=admin state=absent remove=yes