---
- name: Install software-properties-common
  apt: name=software-properties-common state=present

- name: Add stable nginx repository
  apt_repository: repo='ppa:ansible/ansible'

- name: Install Ansible
  apt: name=ansible state=present update_cache=yes