---
- hosts: droplets
  serial: 2
  remote_user: root

  vars_files:
    - vars/instance.yml

  pre_tasks:
    - name: Set PHP version for 16.04
      set_fact:
        php_version: 7
      when: ansible_distribution_version == "16.04"

    - name: Set PHP version for 14.04
      set_fact:
        php_version: 5
      when: ansible_distribution_version == "14.04"

  roles:
    - { role: create_instance }
    - { role: letsencrypt, when: (instance_ssl and letsencrypt_cert_create) }