---
- hosts: droplet
  remote_user: root
  gather_facts: no

  vars_files:
    - vars/instance.yml

  tasks:
    - name: Remove user
      user: name={{ instance_name }} state=absent remove=yes

    - name: Remove MySQL database
      mysql_db: >
        login_user=root
        login_password="{{ mysql_root_pass }}"
        name="{{ instance_name }}_{{ instance_env }}"
        state=absent

    - name: Remove MySQL user
      mysql_user: >
        login_user=root
        login_password="{{ mysql_root_pass }}"
        name="{{ instance_name }}"
        state=absent

    - name: Remove instance vhost
      file: path={{ item }} state=absent
      with_items:
        - "/etc/nginx/sites-enabled/{{ instance_name }}_{{ instance_env }}"
        - "/etc/nginx/sites-available/{{ instance_name }}_{{ instance_env }}"