---
- name: restart jenkins
  service: name=jenkins state=restarted enabled=yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: print jenkins key
  debug: msg="JENKINS SSH - {{ jenkins_ssh_key.stdout }}"