---
- name: Check swapfile  
  shell: 'sudo swapon -s | grep -E "^/"'
  register: swapfile  
  ignore_errors: yes 

- name: Write swapfile
  command: fallocate -l {{ swapfile_size }} {{ swapfile_location }}
  register: write_swapfile
  sudo: true
  when: swapfile_size != false and swapfile|failed

- name: Set swapfile permissions
  file: path={{ swapfile_location }} mode=600
  sudo: true
  when: swapfile_size != false

- name: Create swapfile
  command: mkswap {{ swapfile_location }}
  register: create_swapfile
  sudo: true
  when: swapfile_size != false and write_swapfile.changed

- name: Enable swapfile
  command: swapon {{ swapfile_location }}
  sudo: true
  when: swapfile_size != false and create_swapfile.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swapfile_location }} none swap sw 0 0" state=present
  sudo: true
  when: swapfile_size != false