---
- name: Install postfix and dependencies
  apt: name={{ item }} state=present
  with_items:
    - postfix
    - mailutils
    - libsasl2-2
    - ca-certificates
    - libsasl2-modules

- name: Copy postfix configuration
  template: src=main.cf.j2 dest=/etc/postfix/main.cf
  notify:
    - restart postfix
    - send test email

- name: Copy SMTP authentication
  template: src=sasl_passwd.j2 dest=/etc/postfix/sasl/sasl_passwd mode=0400 owner=root group=root
  notify:
    - restart postfix

- name: Prepare sasl DB
  shell: postmap /etc/postfix/sasl/sasl_passwd
  sudo: yes

- name: Copy postfix rewrite
  template: src=rewrite.j2 dest=/etc/postfix/rewrite
  notify:
    - restart postfix
    - send test email

- name: Check if certificate exists
  stat: path=/etc/ssl/certs/Thawte_Premium_Server_CA.pem
  register: thawte_certificate

- name: Validate certificate
  shell: cat /etc/ssl/certs/Thawte_Premium_Server_CA.pem | sudo tee -a /etc/postfix/cacert.pem
  when: thawte_certificate.stat.exists
  notify:
    - restart postfix

- name: Copy certificate
  template: >
    src=thawte_Premium_Server_CA.pem.j2
    dest=/etc/postfix/cacert.pem
  when: thawte_certificate.stat.exists == False
  notify:
    - restart postfix

- name: Start postfix on server boot
  service: name=postfix state=started enabled=yes