---
- hosts: droplet
  remote_user: root
  gather_facts: no

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Set bash as default shell for root user
      user: name=root shell=/bin/bash

    - name: Remove sudo user
      user: name="{{ sudo_user_name }}" state=absent remove=yes

    - name: Fix Uninstall
      shell: dpkg --configure -a

    - name: Uninstall all packages
      apt: pkg={{ item }} state=absent purge=yes force=yes
      with_items:
        - nginx*
        - mysql*
        - php*
        - git*
        - ntp*
        - zsh*
        - nodejs*
        - npm*
        - postfix*
        - mailutils*
      sudo: yes

    - file: path={{ item }} state=absent
      with_items:
        - /var/lib/mysql
        - /var/log/mysql
        - /etc/mysql
        - /etc/nginx
        - /usr/local/src/.oh-my-zsh
        - ~/.zshrc
        - /usr/local/bin/composer
        - /usr/local/src/drush
        - /usr/bin/drush
        - /etc/postfix