---
- hosts: droplets
  gather_facts: false
  serial: 2
  remote_user: root
  tasks:
    - name: Install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: droplets
  serial: 2
  remote_user: root

  vars_files:
    - vars/vars.yml

  pre_tasks:
    - name: Update aptitude
      apt: update_cache=yes

    - name: Set PHP version for 16.04
      set_fact:
        php_version: 7
      when: ansible_distribution_version == "16.04"

    - name: Set PHP version for 14.04
      set_fact:
        php_version: 5
      when: ansible_distribution_version == "14.04"

  roles:
    - common
    - swap
    - ntp
    - nginx
    - php-fpm
#    - hhvm
    - mariadb
    - drush
#    - phpcodesniffer
    - nodejs
    - newrelic
    - fail2ban
    - postfix
#    - { role: elasticsearch, es_instance_name: "node1" }
#    - jenkins
#    - gitlab