---
- name: Install MariaDB
  apt: name=mariadb-server state=present
  register: install_mariadb

- name: Install MySQLdb Python
  apt: name=python-mysqldb state=present

- name: Delete anonymous MariaDB server user
  mysql_user: name='' host=localhost state=absent
  when: install_mariadb.changed

- name: Remove the MariaDB test database
  mysql_db: name=test state=absent
  when: install_mariadb.changed

- name: Change root user password
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_root_pass }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: install_mariadb.changed

- name: Create MariaDB configuration file
  template: src=my.cnf dest=/etc/mysql/conf.d/override.cnf owner=root mode=0600
  notify: 
  - restart mysql

- name: Start MariaDB Service
  service: name=mysql state=started