---
- name: Generate password hash for root user
  shell: python -c 'import crypt; print crypt.crypt("{{ root_pass }}", "$1$afRgT$")'
  register: root_pass_hash

- name: Set new root password and name
  user: name="root" comment="{{ root_comment }}" password="{{ root_pass_hash.stdout }}"

- name: Set timezone
  copy: content="{{ timezone }}"
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - update timezone

- name: Install curl
  apt: name=curl state=present

- name: Install python-passlib
  apt: name=python-passlib state=present

- name: Install python-passlib
  apt: name=python-passlib state=present

- name: Add sudo group
  group: name=sudo state=present

- name: Generate password hash for "{{ sudo_user_name }}"
  shell: python -c 'import crypt; print crypt.crypt("{{ sudo_user_pass }}", "$1$afRgT$")'
  register: sudo_user_pass_hash

- name: Add "{{ sudo_user_name }}" user
  user: name="{{ sudo_user_name }}" shell=/bin/zsh comment="{{ sudo_user_comment }}" group=sudo password="{{ sudo_user_pass_hash.stdout }}"

- name: Copy .zshrc for "{{ sudo_user_name }}" user
  command: cp /root/.zshrc "/home/{{ sudo_user_name }}"

- name: Change motd
  template: src=10-help-text.j2 dest=/etc/update-motd.d/10-help-text