---
- name: Set distr version to php5
  set_fact:
    distr: "php5"
    intsall_path: "/etc/php5"
  when: php_version == 5

- name: Set distr version to php7.0
  set_fact:
    distr: "php7.0"
    intsall_path: "/etc/php/7.0"
  when: php_version == 7

- name: Configure the New Relic apt repository
  shell: echo deb http://apt.newrelic.com/debian/ newrelic non-free > /etc/apt/sources.list.d/newrelic.list

- name: Trust the New Relic GPG key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg state=present
  register: new_relic_key

- name: Update cache
  apt: update_cache=yes
  when: new_relic_key.changed

- name: Run the install command
  apt: name=newrelic-sysmond state=present

- name: Add license key to config file
  shell: nrsysmond-config --set license_key={{ new_relic_license_key }}

- name: Start the daemon
  shell: /etc/init.d/newrelic-sysmond start

- name: Install newrelic-php5
  apt: name=newrelic-php5 state=present

- name: Configure newrelic-php5
  shell: newrelic-install install

- name: Remove unnecesarry files
  file: path={{ item }} state=absent
  with_items:
   - "{{ intsall_path }}/cli/conf.d/newrelic.ini"
   - "{{ intsall_path }}/fpm/conf.d/newrelic.ini"

- name: Set license key
  replace:
    dest={{ item }}
    regexp='newrelic.license = .+'
    replace='newrelic.license = "{{ new_relic_license_key }}"'
  notify: restart php-fpm
  with_items:
    - "{{ intsall_path }}/mods-available/newrelic.ini"

- name: Rename application
  replace:
    dest={{ item }}
    regexp='newrelic.appname = .+'
    replace='newrelic.appname = "{{ ansible_hostname }}"'
  notify: restart php-fpm
  with_items:
    - "{{ intsall_path }}/mods-available/newrelic.ini"